---
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secrets
  namespace: nextcloud
type: Opaque
data:
  db-name: base64-encoded-db-name
  db-user: base64-encoded-db-user
  db-pass: base64-encoded-db-pass
  supertokens-conn-uri: base64-encoded-supertokens-conn-uri
  supertokens-api-key: base64-encoded-supertokens-api-key