---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-db-claim
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nextcloud-storage-class
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-redis-claim
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nextcloud-storage-class
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data-claim
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nextcloud-storage-class
  resources:
    requests:
      storage: 50Gi